remote_theme: pages-themes/cayman@v0.2.0
title: Claude Code 高级中文教程
description: 最全面的 Claude Code 中文学习指南，深挖未公开功能，提升开发效率60-80%
author: cfrs2005
github:
  repository_url: https://github.com/cfrs2005/claude-guild-chinese
  is_project_page: true

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# 导航
header_pages:
  - index.md
  - COURSE-GUIDE.md
  - 01-核心概念和导航.md
  - 02-斜杠命令和集成系统.md
  - 03-开发工作流和最佳实践.md
  - 04-Meta-Todo智能任务系统.md
  - 05-高级协同实现.md
  - 06-快速参考和核心概念.md

# 样式设置
show_downloads: false
google_analytics: G-XXXXXXXXXX

# 语言设置
lang: zh-CN

# 日期格式
date_format: "%Y-%m-%d"

# 社交链接
social_links:
  github: cfrs2005
  custom:
    - name: Website
      url: https://claude-code.80aj.com
      icon: fas fa-globe