remote_theme: just-the-docs/just-the-docs@v0.8.2
title: Claude Code 高级中文教程
description: 最全面的 Claude Code 中文学习指南，深挖未公开功能，提升开发效率60-80%
author: cfrs2005

# Just the Docs 配置
url: "https://claude-code.80aj.com"
baseurl: ""

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# 搜索配置
search:
  enabled: true
  placeholder: "搜索文档..."

# 导航配置
nav_sorting: case_sensitive
heading_anchors: true

# 颜色主题
color_scheme: light

# Aux links
aux_links:
  "GitHub 仓库": "https://github.com/cfrs2005/claude-guild-chinese"

# 按钮
aux_links_new_tab: true

# 社交链接
social_links:
  github: cfrs2005

# 语言设置
lang: zh-CN