remote_theme: just-the-docs/just-the-docs@v0.8.2
title: Claude Code 高级中文教程
description: 最全面的 Claude Code 中文学习指南，深挖未公开功能，提升开发效率60-80%
author: cfrs2005

# Just the Docs 配置
url: "https://claude-code.80aj.com"
baseurl: ""

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Just the Docs 特定配置
search:
  enabled: true
  placeholder: "搜索 Claude Code 教程..."
  # 搜索结果预览
  previews: 8
  # 搜索结果显示范围
  scope:
    path: "_posts"
    type: "posts"

# 导航配置
nav_sorting: case_sensitive
heading_anchors: true

# 启用目录
nav_external_links:
  - title: GitHub 仓库
    url: https://github.com/cfrs2005/claude-guild-chinese

# 颜色主题
color_scheme: light

# 侧边栏配置
sidebar:
  sticky: true
  level_depth: 3

# 启用页内目录
nav_fold: false
back_to_top: true
back_to_top_text: "返回顶部"

# 呼出链接
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red

# 代码高亮
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Aux links
aux_links:
  "GitHub 仓库": "https://github.com/cfrs2005/claude-guild-chinese"
  "在线文档": "https://claude-code.80aj.com"

# 按钮
aux_links_new_tab: true

# 社交链接
social_links:
  github: cfrs2005

# 语言设置
lang: zh-CN

# 排除文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .specstory/
  - README.md
  - LICENSE# Last updated: 2025年 9月20日 星期六 00时36分14秒 CST
